backend:
  name: git-gateway
  repo: a0smile/anayh-smile
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/bc92069e-6d76-4a6b-9ddb-7c3937ae10ba/pkce
  auth_token_endpoint: /sites/bc92069e-6d76-4a6b-9ddb-7c3937ae10ba/token
  gateway_url: https://gateway.decapbridge.com